services:
  scrumboardapi:
    image: scrumboardapi
    build:
      context: .
      dockerfile: ScrumboardApi/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  scrumboardapi-1:
    image: scrumboardapi-1
    build:
      context: .
      dockerfile: ScrumboardApi/Dockerfile

  scrumboard.frontend:
    image: scrumboard.frontend
    build:
      context: .
      dockerfile: Scrumboard.FrontEnd/Dockerfile

